#!/usr/bin/env bash
# SPDX-FileCopyrightText: Veredictum contributors
# SPDX-License-Identifier: Apache-2.0
# The committed command reference is what the binary's help renders to (#466).
#
# This guard used to hold three hand-written copies of the CLI surface to
# clap's `--help`: the binary's header table, the root `CLAUDE.md` "canonical
# CLI table", and the book's command reference (#76). It compared subcommand
# NAMES, because holding every flag row to clap would have made the guard a
# second parser. The copies are gone. The book page is GENERATED by
# `scripts/render/commands-md.sh` out of `veredictum <subcommand> --help`, and
# the other two now point at `--help` and at that page instead of restating it.
#
# So what is left to check is one thing: the committed page is still what the
# generator produces from this tree's binary. The generator writes to a
# temporary file and the bytes are compared, which also catches a subcommand
# added to clap and never rendered, a flag whose help text moved, and a stale
# partial under `website/book/commands`.
#
# Usage: scripts/checks/cli-surface.sh
#   The generator reads `target/debug/veredictum` when that binary exists (the
#   CI test job has already built it), otherwise it builds through
#   `cargo run --quiet --locked`.
set -euo pipefail
cd "$(dirname "$0")/../.."

BOOK=website/book/src/commands.md

rendered="$(mktemp)"
trap 'rm -f "$rendered"' EXIT

bash scripts/render/commands-md.sh "$rendered" >/dev/null

if ! diff -u "$BOOK" "$rendered" --label "$BOOK (committed)" --label "$BOOK (rendered)"; then
  echo "::error::${BOOK} is stale — regenerate it with \`bash scripts/render/commands-md.sh\` and commit the result" >&2
  exit 1
fi

echo "cli-surface: ${BOOK} is byte-identical to the binary's own help — OK."
